name: Run VK Script Hourly

on:
  schedule:
    - cron: '0 * * * *'  # Запускать каждый час

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install vk_api

    - name: Run script
      env:
        TOKEN: ${{ secrets.TOKEN }}
        GROUP_ID: ${{ secrets.GROUP_ID }}
        USER_ID: ${{ secrets.USER_ID }}
      run: python main.py
